version: "3"

services:
  node:
    user: 1000:1000
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: npm exec -w viewer-test parcel index.html
    ports:
      - 1234:1234
      - 1235:1235
